sctvsearch/Search_Invoice/Search_Invoice/Controllers/PageHomeController.cs
using Newtonsoft.Json.Linq;
using Search_Invoice.Data;
using Search_Invoice.Data.Domain;
using Search_Invoice.Models;
using Search_Invoice.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using Search_Invoice.DAL;
using LicenseContext = System.ComponentModel.LicenseContext;
using Search_Invoice.Util;

namespace Search_Invoice.Controllers
{
    public class PageHomeController : Controller
    {
        private INopDbContext _nopDbContext;

        // GET: PageHome

        [AllowAnonymous]
        public ActionResult PageHomeIndex()
        {
            return View();
        }

        [AllowAnonymous]
        public PartialViewResult PageHomeHeader()
        {
            return PartialView("PageHomeHeader");
        }
        [AllowAnonymous]
        public ActionResult ExportExcel()
        {
            var us = (inv_user_tax)Session[CommonConstants.USER_SESSION_TAX];
            if (us == null)
                return RedirectToAction("LoginTax", "Account");
            return View();
        }
        [DeleteFileDown]
        [HttpGet]
        public FileResult GetFile(string path)
        {
            var result = new FilePathResult(path, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            {
                FileDownloadName = new FileInfo(path).Name
            };
            return result;
        }
        [HttpPost]
        public JsonResult GetDataCompany()
        {
            var dbContext = new TracuuHDDTContext();
            var list = dbContext.company.Select(c => new { c.taxcode, c.name });
            return Json(new { data = list, MaxJsonLength = int.MaxValue }, JsonRequestBehavior.AllowGet);
        }

        private const int RecordsPerPage = 10048575;

        [HttpPost]
        public async Task<JsonResult> ExportAll(string startDate, string endDate)
        {
            try
            {
                var us = (inv_user_tax)Session[CommonConstants.USER_SESSION_TAX];
                if (us == null)
                    return Json(JsonConvert.SerializeObject(new { status = 500 }), JsonRequestBehavior.AllowGet);
                var dbContext = new TracuuHDDTContext();
                //select * from reg.getcntmaster('2020-10-24','2020-12-30')
                DateTime dt;
                if (DateTime.TryParseExact(startDate, "yyyy-MM-dd hh:mm:ss", System.Globalization.CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None, out dt))
                    startDate = dt.ToString("yyyy-MM-dd");
                if (DateTime.TryParseExact(endDate, "yyyy-MM-dd hh:mm:ss", System.Globalization.CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None, out dt))
                    endDate = dt.ToString("yyyy-MM-dd");
                var schemaTest = ConfigurationManager.AppSettings["schema_test"];

                string sqlMaster = "SELECT * FROM #SCHEMA_NAME#.getcntmaster(@startDate,@endDate,@schemaTest)";
                string sqlDetail = "SELECT * FROM #SCHEMA_NAME#.getcntdetail(@startDate,@endDate,@schemaTest)";

                Dictionary<string, object> parameters = new Dictionary<string, object>();
                parameters.Add("startDate", startDate);
                parameters.Add("endDate", endDate);
                parameters.Add("schemaTest", schemaTest);

                var cntMaster = Convert.ToInt32((await dbContext.GetDataTableAsync(us.schema_url, "reg", sqlMaster, parameters)).Rows[0][0].ToString());

                var cntDetail = Convert.ToInt32((await dbContext.GetDataTableAsync(us.schema_url, "reg", sqlDetail, parameters)).Rows[0][0].ToString());

                var ds = new DataSet();
                var pageMaster = (cntMaster + RecordsPerPage - 1) / RecordsPerPage;
                var pageDetail = (cntDetail + RecordsPerPage - 1) / RecordsPerPage;
                var headers = HeaderMasters();
                var headersDetail = HeaderDetails();
                for (var i = 1; i <= pageMaster; i++)
                {

                    string sqlDataMaster = "SELECT * FROM #SCHEMA_NAME#.getdatamaster(@records,@RecordsPerPage,@startDate,@endDate,@schemaTest)";

                    parameters = new Dictionary<string, object>();
                    parameters.Add("records", (i - 1) * RecordsPerPage);
                    parameters.Add("RecordsPerPage", RecordsPerPage);
                    parameters.Add("startDate", startDate);
                    parameters.Add("endDate", endDate);
                    parameters.Add("schemaTest", schemaTest);

                    var d = await dbContext.GetDataTableAsync(us.schema_url, "reg", sqlDataMaster, parameters);
                    d.TableName = "HOADON_MASTER" + (pageMaster > 1 ? $"{i}" : "");
                    d.Columns.Remove("schema_name");
                    //var cols = d.Columns.Cast<DataColumn>().Where(c=>c.ColumnName != "schema_name").ToArray();
                    for (var c = 0; c < d.Columns.Count; c++)
                        d.Columns[c].ColumnName = headers[c];
                    d.AcceptChanges();
                    ds.Tables.Add(d);

                }

                for (var i = 1; i <= pageDetail; i++)
                {

                    string sqlDataDetail = "SELECT * FROM #SCHEMA_NAME#.getdatadetail(@records,@RecordsPerPage,@startDate,@endDate,@schemaTest)";

                    parameters = new Dictionary<string, object>();
                    parameters.Add("records", (i - 1) * RecordsPerPage);
                    parameters.Add("RecordsPerPage", RecordsPerPage);
                    parameters.Add("startDate", startDate);
                    parameters.Add("endDate", endDate);
                    parameters.Add("schemaTest", schemaTest);

                    var d = await dbContext.GetDataTableAsync(us.schema_url, "reg", sqlDataDetail, parameters);
                    d.TableName = "HOADON_DETAIL" + (pageDetail > 1 ? $"{i}" : "");
                    d.Columns.Remove("schema_name");
                    //var cols = d.Columns.Cast<DataColumn>().Where(c=>c.ColumnName != "schema_name").ToArray();
                    for (var c = 0; c < d.Columns.Count; c++)
                        d.Columns[c].ColumnName = headersDetail[c];
                    d.AcceptChanges();
                    ds.Tables.Add(d);
                }

                var a = from DataColumn d in ds.Tables[0].Columns select d;
                var file = System.Web.HttpContext.Current.Server.MapPath($"~/Content/report/ExportData_{DateTime.Now:yyyyMMddhhmmss}.xlsx");
                // var file = $"ExportData_{DateTime.Now:yyyyMMddhhmmss}.xlsx";
                ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

                using (var excel = new ExcelPackage(new FileInfo(file)))
                {
                    for (var i = 0; i < ds.Tables.Count; i++)
                    {
                        var ws = excel.Workbook.Worksheets.Add(ds.Tables[i].TableName);
                        var dateColumns = from DataColumn d in ds.Tables[i].Columns
                                          where d.DataType == typeof(DateTime) || d.ColumnName.Contains("Date")
                                          select d.Ordinal + 1;
                        var decimalColumns = from DataColumn d in ds.Tables[i].Columns
                                             where d.DataType == typeof(decimal)
                                             select d.Ordinal + 1;
                        ws.View.FreezePanes(2, 1);
                        ws.Cells[1, 1, 1, ds.Tables[i].Columns.Count].AutoFilter = true;

                        ws.Cells.LoadFromDataTable(ds.Tables[i], true);
                        ws.Cells.AutoFitColumns();
                        //format date
                        foreach (var d in dateColumns)
                        {
                            ws.Column(d).Style.Numberformat.Format = "dd/mm/yyyy";
                        }
                        //format number
                        foreach (var d in decimalColumns)
                        {
                            ws.Column(d).Style.Numberformat.Format = "0.0000";
                        }
                        ws.Column(13).Style.Numberformat.Format = "0.00"; // column Tỷ giá
                        // column số thứ tự
                        if (ds.Tables[i].TableName.Contains("HOADON_DETAIL"))
                            ws.Column(8).Style.Numberformat.Format = "0";
                        if (ds.Tables[i].TableName.Contains("HOADON_MASTER"))
                            ws.Column(8).Style.Numberformat.Format = "@";
                    }
                    await excel.SaveAsync();
                }

                return Json(JsonConvert.SerializeObject(new
                {
                    status = 200,
                    path = file
                }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(JsonConvert.SerializeObject(new
                {
                    status = 400,
                    e.Message
                }), JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public async Task<JsonResult> GetData(string startDate, string endDate, int page, int pageSize)
        {
            //string startDate = "", endDate= "";
            DateTime dt;
            if (DateTime.TryParseExact(startDate, "yyyy-MM-dd hh:mm:ss", System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.None, out dt))
                startDate = dt.ToString("yyyy-MM-dd");

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/Header.cshtml
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <div class="top-left-part">
            <a class="logo" href="javascript:void(0)">
                <span class="hidden-xs"><img src="~/MobifoneUICustomer/img/logo1.png" alt="home" width="140" /></span>
            </a>
        </div>

        <ul class="nav navbar-top-links navbar-right pull-right" id="user_head">
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">

                    <b class="hidden-xs">@User.Identity.Name.ToUpper()</b>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    @*<li><a href="#">My Profile</a></li>*@
                    <li role="separator" class="divider"></li>
                    <li><a onclick="abc();">Đổi mật khẩu</a></li>
                    <li><a href="/Account/LogOff">Đăng xuất</a></li>
                </ul>
                <!-- /.dropdown-user -->
            </li>

        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/HeaderTax.cshtml
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        @*<a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>*@
        <div class="top-left-part">
            <a class="logo" href="javascript:void(0)">
                <span class=""><img src="~/MobifoneUICustomer/img/logo1.png" alt="home" width="140" /></span>
            </a>
        </div>

        <div class="nav navbar-nav mx-auto navbar navbar-expand-sm bg-light justify-content-center top-center-part">
            Hệ thống tra cứu hóa đơn điện tử SCTV
        </div>

        <ul class="nav navbar-top-links navbar-right pull-right" id="user_head">
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">

                    <b class="">@User.Identity.Name.ToUpper()</b>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                      @*<li><a href="#">My Profile</a></li>
                    <li role="separator" class="divider"></li>*@
                   @* <li><a onclick="abc();">Đổi mật khẩu</a></li>*@
                    <li><a href="/Account/LogOut">Đăng xuất</a></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/Sidebar.cshtml
<div class="col-md-2">
    <h1 style="font-weight: bold;font-size: 25px; color: #005EB2; text-align: center;">Tra cứu hóa đơn</h1>
</div>

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/_Danhmuc.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section>
    <div class="row bg-title">
        @RenderSection("ContentHeader", false)
    </div>
</section>

<section class="content" style="padding-left:0px !important;padding-right:0px !important">
    <div class="white-box1">
        <div class="box-title">
            @RenderSection("BoxTitle", false)
        </div>
        <style>
            .k-grid-content > table > tbody > tr {
                background: White;
            }

            .modal-dialog {
                /*height: 80% !important;*/
                padding-top: 10%;
            }

            .modal-content {
                /*height: 100% !important;*/
                overflow: visible;
            }

            .modal-body {
                /*height: 70%;*/
                overflow: auto;
            }
        </style>
        @RenderSection("BoxBody", false)
    </div>
    @RenderSection("BoxFooter", false)
</section>

@RenderSection("Scripts", false)

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="vi">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="http://tracuuhoadon.minvoice.vn/Content/plugins/images/fa-icon.png">

    <title>Hóa đơn điện tử Mobi-Invoice</title>

    <!-- Bootstrap Core CSS -->
    <link href="/Content/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/plugins/bower_components/bootstrap-extension/css/bootstrap-extension.css" rel="stylesheet">
    <!-- animation CSS -->
    <link href="/MobifoneUICustomer/css/animate.css" rel="stylesheet">
    <!-- Footable CSS -->
    <link href="/Content/plugins/bower_components/footable/css/footable.core.css" rel="stylesheet">
    <link href="/Content/plugins/bower_components/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
    <!-- Menu CSS -->
    <link href="/Content/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/MobifoneUICustomer/css/style.css" rel="stylesheet">
    <!-- color CSS gray/blue/purple/megna/default -->
    @*<link href="/Content/css/colors/default.css" id="theme" rel="stylesheet">*@
    <!-- Kendo Style CSS -->
    @*<link rel="stylesheet" href="/Content/kendo/styles/kendo.common-bootstrap.min.css">*@
    @*<link rel="stylesheet" href="/Content/kendo/styles/kendo.bootstrap.min.css">*@
    <!--alerts CSS -->
    <link href="/Content/plugins/bower_components/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
    <link rel='stylesheet' id='font-awesome-css' href='~/UI/tracuu.minvoice.vn/wp-content/themes/minvoice/css/fontawesome/css/all0e7d.css?ver=5.1.0' type='text/css' media='all' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="/Content/plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Content/bootstrap/dist/js/tether.min.js"></script>
    <script src="/Content/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/Content/plugins/bower_components/bootstrap-extension/js/bootstrap-extension.min.js"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="/Content/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
    <!--slimscroll JavaScript -->
    <script src="/Content/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="/Content/js/waves.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Content/js/custom.min.js"></script>
    <script src="/Content/js/jasny-bootstrap.js"></script>
    <!--Style Switcher -->
    <script src="/Content/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
    <script src="/Content/plugins/chartjs/Chart.min.js"></script>
    <!-- Footable -->
    <script src="/Content/plugins/bower_components/footable/js/footable.all.min.js"></script>
    <script src="/Content/plugins/bower_components/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
    <!--FooTable init-->
    <script src="/Content/plugins/footable-init.js"></script>
    <!-- bootbox  -->
    <script src="/Scripts/bootbox.min.js"></script>
    <!-- ment.js  -->
    <script src="~/Scripts/moment.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
</head>

<body class="fix-header">
    <!-- Preloader -->
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>
    <div id="wrapper">
        @Html.Action("Header", "Home")

        <!-- Left side column. contains the logo and sidebar -->
        <!-- Content Wrapper. Contains page content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <section class="content" style="padding-left:0px !important;padding-right:0px !important">
                    <div class="row">
                        @Html.Action("Sidebar", "Home")
                        <div class="col-md-10 white-box1">
                            <div class="box-title">

                            </div>
                            @RenderBody()
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <script type="text/javascript">
        function abc() {
            bootbox.confirm("<form class='doimk' id='infos' action=''>\
        Mật khẩu cũ:<input class = 'form-control' type='text' name='password' /><br/>\
        Mật khẩu mới:<input class = 'form-control' type='text' name='newpassword' /><br/>\
        Nhập lại mật khẩu:<input class = 'form-control' type='text' name='renewpassword' />\
        </form>", function (result) {
        if (result) {
            var jk = $("#infos").serialize();
            //console.log(jk);

            $.ajax({
                url: "/Account/ChangePassword_Use",
                type: "POST",
                data: jk,
                success: function (result) {

                    result = JSON.parse(result);
                    if (!result.hasOwnProperty("error")) {

                        bootbox.alert("Đổi mật khẩu thành công !");
                        $.get("/Account/Logoff", function (data) {
                        });
                    }
                    else {
                        bootbox.alert(result.error);
                    }
                }
            });
        }
    });
    }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/_PageHomeLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tra cứu hóa đơn điện tử SCTV</title>
    <!-- Jquery -->
    <script src="~/Content/plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <link rel='stylesheet' id='font-awesome-css' href='~/UI/tracuu.minvoice.vn/wp-content/themes/minvoice/css/fontawesome/css/all0e7d.css?ver=5.1.0' type='text/css' media='all' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Font Icon -->

    <link rel="stylesheet" href="~/MobifoneUI/fonts/material-icon/css/material-design-iconic-font.min.css">
    <!-- Bootstrap + Bootbox -->
    <link rel='stylesheet' id='bootstrap_css-css' href='~/UI/maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min37cb.css?ver=4.9.7' type='text/css' media='all' />
    <script type='text/javascript' src='~/UI/maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min37cb.js?ver=4.9.7'></script>
    <script type='text/javascript' src='~/UI/tracuu.minvoice.vn/wp-includes/js/bootbox.min.js'></script>
    <!-- Main css -->
    <link rel="stylesheet" href="~/MobifoneUI/css/style.css">
    <!-- Moment -->
    <script src="~/Scripts/moment.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <style>
        body {
            background-image: url(../../MobifoneUI/images/lgn2.jpg);
            /*background-position: center;*/
            height: 500px;
            background-position: center;
            background-size: cover;
            position: relative;
            font-size: 13px;
            line-height: 1.8;
            color: #222;
            font-weight: 400;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }

        .container1-fix {
            display: flex;
            justify-content: center;
        }

        .signup-content1 {
            width: 500px;
            background: #fff;
            box-shadow: 0px 15px 16.83px 0.17px rgba(0, 0, 0, 0.05);
        }

        .huongdan-fix {
            display: flex;
            justify-content: space-between;
            flex-flow: column;
            margin-right: 4%;
            flex-basis: 20%;
        }

        .logo-fix {
            width: 50%;
            transform: translate(0%, -24%);
        }

        .gt-fix {
            display: flex;
            margin-top: 2%;
        }

        .Hotline-fix {
            margin-right: 7%;
        }

        .right {
            margin-left: 4%;
        }

        .btn {
            color: white;
            font-size: 0.85rem;
            font-weight: bold;
            background-image: linear-gradient(to right, #005FB4, #0097D9);
            padding: 0.5rem 0.75rem;
            border-radius: 20px;
        }

        .signup-form-fix {
            padding-left: 5%;
            padding-right: 5%;
            padding-top: 5%;
        }

        .aaaa {
            position: relative;
            display: flex;
            justify-content: center;
            margin-top: 10%;
        }

            .aaaa::before {
                display: block;
                content: '';
                width: 100%;
                height: 1px;
                background-color: #e9e1e1;
                position: absolute;
            }

        .text-block {
            display: inline-block;
            width: 54%;
        }

        .texttt {
            text-align: center;
            margin: 0;
            background-color: white;
        }
    </style>
</head>
<body>
    <!-- <div class="header">

    </div> -->

    <div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container1-fix">
                @Html.Action("PageHomeHeader", "PageHome")
                @RenderBody()
                <div class="right">
                    <a class="btn" href="/dang-nhap" style="text-decoration: none;">Tra cứu Doanh nghiệp</a>
                </div>
            </div>
        </section>

        <!-- Sing in  Form -->

    </div>

    <!-- JS -->
    @*<script src="~/MobifoneUI/vendor/jquery/jquery.min.js"></script>*@
    <script src="~/MobifoneUI/js/main.js"></script>

    @RenderSection("scripts", required: false)
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

sctvsearch/Search_Invoice/Search_Invoice/Views/Shared/_Pager.cshtml
@using Search_Invoice.Models;
@model Pager
<ul class="pagination pull-left">
    <li class="page-item" style="font-weight: bold;">Tổng số : @Model.TotalItems</li>
</ul>
<ul class="pagination pull-right">
    @{
        var numberPage = Model.NumberPage;
        var currentPage = Model.PageCurrent;
        var offset = Model.Offset;//number display page
        var total = Model.TotalItems;
        if (currentPage > 1)
        {
            var prevPage = currentPage - 1;
            <li>
                <a href="javascript:void(0)" page="@prevPage">Prev</a>
            </li>
        }
        const int pageLeft = 5;
        const int pagesRight = 5;
        var fromPage = Math.Max(1, currentPage - pageLeft);
        //var fromPage = currentPage;// Math.Max(currentPage, currentPage > pageLeft ? currentPage : 1);

        var toPage = Math.Min(numberPage, currentPage + pagesRight);
        if (numberPage - toPage == 1)
        {
            toPage = numberPage;
        }
        if (fromPage > 1)
        {
            <li>
                <a href="javascript:void(0)" page="1">1</a>
            </li>
            if (fromPage > 2)
            {
                var middleNumber = Math.Max(1, currentPage - pageLeft);// (int)Math.Ceiling((double)(fromPage - pageLeft) / pageLeft + 1);
                <li>
                    <a href="javascript:void(0)" page="@middleNumber">...</a>
                </li>
            }
        }
        for (var i = fromPage; i <= toPage; i++)
        {
            <li @Html.Raw(currentPage == i ? "class=\"page-item active\"" : "")>
                <a href="javascript:void(0)" page="@i">@i</a>
            </li>
        }
        if (toPage < numberPage)
        {
            var middleNumber = Math.Min(numberPage, toPage + pagesRight);// (int)Math.Ceiling((double)(numberPage - toPage) / pagesRight) + toPage;
            <li>
                <a  href="javascript:void(0)" page="@middleNumber">...</a>
            </li>
            if (toPage < numberPage - 1)
            {
                <li>
                    <a  href="javascript:void(0)" page="@numberPage">@numberPage</a>
                </li>
            }
        }
        if (currentPage < numberPage)
        {
            var nextPage = currentPage + 1;
            <li>
                <a href="javascript:void(0)" page="@nextPage">Next</a>
            </li>
        }
    }
</ul>